#!/bin/bash
ln -sf ~/src/github.com/dotfiles/.vimrc ~/.vimrc
ln -sf ~/src/github.com/dotfiles/.zshrc ~/.zshrc
ln -sf ~/src/github.com/dotfiles/vim/autoload ~/.vim
ln -sf ~/src/github.com/dotfiles/vim/colors ~/.vim
ln -sf ~/src/github.com/dotfiles/vim/after ~/.vim
ln -sf ~/src/github.com/dotfiles/vim/indent ~/.vim
ln -sf ~/src/github.com/dotfiles/vim/bundle ~/.vim
ln -sf ~/src/github.com/dotfiles/vim/rc ~/.vim
ln -sf ~/src/github.com/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/src/github.com/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/src/github.com/dotfiles/emacs.d ~/.emacs.d
ln -sf ~/src/github.com/dotfiles/powerline ~/.config/powerline
ln -sf ~/src/github.com/dotfiles/fish ~/.config/fish
ln -sf ~/src/github.com/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/src/github.com/dotfiles/atom/config.cson ~/.atom/config.cson
ln -sf ~/src/github.com/dotfiles/atom/styles.less ~/.atom/styles.less
ln -sf ~/src/github.com/dotfiles/.tigrc ~/.tigrc
ln -sf ~/src/github.com/dotfiles/.irbrc ~/.irbrc
